Repository jonmenard007/SYSC4806-Project, pull requests merged in 2021-03, with the labels that each got.

#3 Rohil
  README.md
  milestone1.class.violet.html
  milestone1.png
Labels: documentation

#18 Add isClosed attribute to Survey
  src/main/java/org/surveymonkey/models/Survey.java
Labels: enhancement

#20 Add test for isClosed() and markAsClosed() functions, and add Javadocs
  src/main/java/org/surveymonkey/models/ChoiceQuestion.java
  src/main/java/org/surveymonkey/models/NumberQuestion.java
  src/main/java/org/surveymonkey/models/Question.java
  src/main/java/org/surveymonkey/models/Survey.java
  src/main/java/org/surveymonkey/models/TextQuestion.java
  src/test/java/SurveyTest.java
Labels: unit tests

#38 User controller for creation, logon added
  src/main/java/org/surveymonkey/controllers/SurveyController.java
  src/main/java/org/surveymonkey/controllers/UserController.java
  src/main/java/org/surveymonkey/models/User.java
  src/main/java/org/surveymonkey/repositories/UserRepository.java
Labels: enhancement

#52 Move "Create Question" Form
  src/main/java/org/surveymonkey/controllers/SurveyController.java
  src/main/resources/templates/createQuestion.html
  src/main/resources/templates/doSurvey.html
Labels: enhancement

#60 Switch to ENV variables
  src/main/resources/application.properties
Labels: enhancement

#75 Reduce max connections
  src/main/resources/application.properties
Labels: bug

#77 Add close survey and view responses functionality
  src/main/java/org/surveymonkey/controllers/SurveyController.java
  src/main/resources/templates/doSurvey.html
  src/main/resources/templates/viewResponses.html
Labels: enhancement

#74 Remove old Form model
  src/main/java/org/surveymonkey/models/Form.java
  src/main/java/org/surveymonkey/repositories/FormRepository.java
  src/main/java/org/surveymonkey/services/FormService.java
  src/main/java/org/surveymonkey/services/iservices/IFormService.java
Labels: refactor

#81 Few small fixes to UI & button text
  src/main/resources/templates/doSurvey.html
  src/main/resources/templates/fillSurvey.html
  src/main/resources/templates/viewResponses.html
Labels: enhancement
