Repository jonmenard007/SYSC4806-Project, pull requests merged in 2021-04, with the labels that each got.

#95 Updated SurveyController to link Surveys and Users during creation
  src/main/java/org/surveymonkey/controllers/SurveyController.java
  src/main/resources/templates/displayAllOpenSurveys.html
  src/main/resources/templates/displayUserSurveys.html
  src/main/resources/templates/userManagement.html
Labels: enhancement

#96 Added unit test for EndUser, updated Javadoc for Model
  src/main/java/org/surveymonkey/models/ChoiceQuestion.java
  src/main/java/org/surveymonkey/models/EndUser.java
  src/main/java/org/surveymonkey/models/NumberQuestion.java
  src/main/java/org/surveymonkey/models/Question.java
  src/main/java/org/surveymonkey/models/Survey.java
  src/test/java/org/surveymonkey/unit/TestEndUser.java
  src/test/java/org/surveymonkey/unit/TestNumberQuestion.java
Labels: documentation, unit tests

#113 Changed display user surveys, so they could manage the survey
  src/main/java/org/surveymonkey/controllers/SurveyController.java
  src/main/java/org/surveymonkey/services/QuestionService.java
  src/main/java/org/surveymonkey/services/SurveyService.java
  src/main/java/org/surveymonkey/services/iservices/ISurveyService.java
  src/main/resources/static/css/statisticContainerStyling.css
  src/main/resources/templates/displayUserSurveys.html
  src/main/resources/templates/viewResponses.html
Labels: enhancement

#118 Add user session support + tests
  src/main/java/org/surveymonkey/controllers/ApplicationController.java
  src/main/java/org/surveymonkey/controllers/ChoiceQuestionController.java
  src/main/java/org/surveymonkey/controllers/EndUserController.java
  src/main/java/org/surveymonkey/controllers/ErrorsController.java
  src/main/java/org/surveymonkey/controllers/NumberQuestionController.java
  src/main/java/org/surveymonkey/controllers/SurveyController.java
  src/main/java/org/surveymonkey/controllers/TextQuestionController.java
  src/main/java/org/surveymonkey/models/Survey.java
  src/main/resources/templates/displayUserSurveys.html
  src/main/resources/templates/fragments/general.html
  src/main/resources/templates/index.html
  src/main/resources/templates/userManagement.html
  src/test/java/org/surveymonkey/integration/ITMock.java
Labels: enhancement

#121 Code CleanUp
  src/main/java/org/surveymonkey/controllers/EndUserController.java
  src/main/java/org/surveymonkey/controllers/SurveyController.java
  src/main/java/org/surveymonkey/models/EndUser.java
  src/main/java/org/surveymonkey/repositories/SurveyRepository.java
  src/main/java/org/surveymonkey/services/SurveyService.java
  src/main/java/org/surveymonkey/services/iservices/ISurveyService.java
  src/main/resources/templates/createUser.html
  src/main/resources/templates/displayAllOpenSurveys.html
  src/main/resources/templates/displayUserSurveys.html
  src/main/resources/templates/doSurvey.html
  src/main/resources/templates/fillSurvey.html
  src/main/resources/templates/userManagement.html
  src/test/java/org/surveymonkey/unit/TestEndUser.java
Labels: enhancement

#132 Fix broken share link
  src/main/java/org/surveymonkey/controllers/ApplicationController.java
Labels: bug
